### ISSUE TITLE
Feature requests for FB 1.7.x

### ISSUE THREAD

**Issue by SlimeDog** [Huskehhh/FakeBlock#12]
Our primary use case is to create a (fake) wall that prevents a player with insufficient permissions from using a 3x2 portal (of our own design, not a nether portal); it looks like:
![Screen Shot 2020-02-16 at 8 33 38 AM](https://user-images.githubusercontent.com/17748923/74608572-115fdb80-5097-11ea-9751-f4cfd15d618b.png)

Feature requests:
- If we use a fence-like block -- for example, IRON_BARS or BLACK_STAINED_GLASS_PANE -- the wall elements do not connect to the frame.
![Screen Shot 2020-02-16 at 8 37 15 AM](https://user-images.githubusercontent.com/17748923/74608616-98ad4f00-5097-11ea-9302-de29cdb2567c.png)
It should look like this.
![Screen Shot 2020-02-16 at 8 40 39 AM](https://user-images.githubusercontent.com/17748923/74608678-1e30ff00-5098-11ea-9f1e-9f774497eb3a.png)
- For the create command, tab-completion for materials would be a huge benefit.
- For the create command, materials entered in lowercase should be converted to uppercase, and accepted.
- If we change the player permission to allow access, they have to disconnect/reconnect for the change to take effect. Is it possible that the (appropriate) permission change would trigger a FakeBlock reset for the player?

**Comment by Huskehhh** [comment]
Just need to do the block data for the fences now. :)

**Comment by SlimeDog** [comment]
The partial blocks include
- fences
  - all wood types
  - iron
- walls
  - all stone & rock & etc types
- glass panes
  - plain
  - stained glass

I will test them all. :)

**Comment by Huskehhh** [comment]
With the permission updating... LuckPerms is currently the only supported permissions plugin, if you use something else, I'm happy to look into supporting it also.

**Comment by SlimeDog** [comment]
That's great! I use LuckPerms. Everyone should do :)

**Comment by SlimeDog** [comment]
Changing permissions under a player does not seem to trigger changes to the fake doors. I still have to re-enter the world for the changes to take effect. Please note that the LuckPerms of interest here are group permissions, not individual player permissions, so inheritance needs to be checked. For example:

FakeBlock/config.yml
```
lobby_city:
  location1:
    ==: org.bukkit.Location
    world: world_lobby
    x: -2.0
    y: 6.0
    z: 6.0
    pitch: 0.0
    yaw: 0.0
  location2:
    ==: org.bukkit.Location
    world: world_lobby
    x: -3.0
    y: 4.0
    z: 6.0
    pitch: 0.0
    yaw: 0.0
  material: BLACK_STAINED_GLASS
```
LuckPerms
```
>perms user PLAYER permission checkinherits fakeblock.lobby_city
[10:51:31] [pool-12-thread-1/INFO]: [LuckPerms] PLAYER has permission fakeblock.lobby_city set to true in context global. (inherited from blackdog)
```
