### ISSUE TITLE
Delayed wall visibility

### ISSUE THREAD

**Issue by SlimeDog** [Huskehhh/FakeBlock#13]
Spigot 1.15.3 (Jenkins 2650)
ProtocolLib 4.5.1-b447
FakeBlock 1.7.2-b58

FakeBlock is now critical to our lobby design, hiding doors from lower ranks. Unfortunately, on a slow client machine, it can take quite a while -- 10+ seconds -- for fake walls to become visible. Is there any hope?

config.yml
```
lobby_city:
  location1:
    ==: org.bukkit.Location
    world: world_lobby
    x: -2.0
    y: 6.0
    z: 6.0
    pitch: 0.0
    yaw: 0.0
  location2:
    ==: org.bukkit.Location
    world: world_lobby
    x: -3.0
    y: 4.0
    z: 6.0
    pitch: 0.0
    yaw: 0.0
  material: IRON_BARS
lobby_whitedog:
  location1:
    ==: org.bukkit.Location
    world: world_lobby
    x: -6.0
    y: 6.0
    z: 3.0
    pitch: 0.0
    yaw: 0.0
  location2:
    ==: org.bukkit.Location
    world: world_lobby
    x: -6.0
    y: 4.0
    z: 2.0
    pitch: 0.0
    yaw: 0.0
  material: IRON_BARS
lobby_yellowdog:
  location1:
    ==: org.bukkit.Location
    world: world_lobby
    x: -6.0
    y: 6.0
    z: -2.0
    pitch: 0.0
    yaw: 0.0
  location2:
    ==: org.bukkit.Location
    world: world_lobby
    x: -6.0
    y: 4.0
    z: -3.0
    pitch: 0.0
    yaw: 0.0
  material: IRON_BARS
```
