### ISSUE TITLE
Wall not passable

### ISSUE THREAD

**Issue by SlimeDog** [Huskehhh/FakeBlock#4]
Spigot 1.14.4
ProtocolLib 4.5.0-b429
FakeBlock 1.6-b16 (Nov 6)

I do not see that anything has changed in processing a wall, compared with 1.6-b10. Here is an example.
> /fakeblock create world_N

and then clicked on the two corners.
![Screen Shot 2019-11-07 at 9 27 37 AM](https://user-images.githubusercontent.com/17748923/68412359-efbe9200-0140-11ea-842e-ab5424057a7b.png)

The wall was recorded in plugins/FakeBlock/config.yml when created (that is good).
```
world_N:
  location1:
    ==: org.bukkit.Location
    world: world
    x: -1.0
    y: 65.0
    z: -45.0
    pitch: 0.0
    yaw: 0.0
  location2:
    ==: org.bukkit.Location
    world: world
    x: 0.0
    y: 64.0
    z: -45.0
    pitch: 0.0
    yaw: 0.0
  material: BLACK_CONCRETE
```
- Note that I changed the material from TNT to BLACK_CONCRETE, which is the material of the selected blocks. (I do not understand why **/fakeblock create** does not identify the material from the selected blocks.)
- I am op (LuckPerms admin), and also have explicit permission for the wall: **fakeblock.world_N** and **fakeblock.admin**.
- I ran **/fakeblock reload**. No joy.
- I rebooted the server. No joy.
- There were no errors in-game or at the console/log.

Result: The wall is still visible and is impassible.

If I change the blocks to TNT, the result is the same.
![Screen Shot 2019-11-07 at 8 07 17 AM](https://user-images.githubusercontent.com/17748923/68412074-7a52c180-0140-11ea-97b1-b15733ca32f2.png)
